services:
  - type: web
    name: productos-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false

